map =[
    ["wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall",],
    ["wp wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","we wall","wp wall",],
    ["wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall","wp wall",],
    ["w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall","w wall",]
];
   



   

